version: '3.8'

services:
    wine-microservice:
        build:
            dockerfile: ./Dockerfile-nginx
        image: wine-microservice
        restart: unless-stopped
        ports:
            - "5000"
        deploy:
            replicas: 2


    nginx-balancer:
        image: nginx
        container_name: nginx-balancer
        restart: unless-stopped
        volumes:
            - ./src/nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - wine-microservice
        ports:
            - "8082:80"
